# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2a83b25729fcb389f88567cbad9bad7e38bb23ccc56334bbf1749e6d40db2fb8317bf35cb151b9310641f3f3fdb4ec5a88f1bb2cff59be1da20b6d546e7b9a7

test:
  secret_key_base: 518683d4a9f97a99c49fdd426d8d2861a8a3cf680a32276d87cade6370c5c84cbd9deb21b803066a4113d0ab48f507ca9ac515b72d501a2f0656573073694ecd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
